# ── Baza de date (Supabase-ul TAU) ──
spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.fiqutwldhmhbsrptlzyo
spring.datasource.password=doubledualcore4

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ── Connection pool ──
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1

# ── Actuator ──
management.endpoints.web.exposure.include=*

# ── Application ──
spring.application.name=PadelLeague
server.port=8080

# ── Mail (optional, can be disabled in production) ──
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mailerso63@gmail.com
spring.mail.password=qhwl aqsz wvbv parj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# URL injected into verification emails and password resets
app.frontend.url=http://localhost:3000